name: third manual run workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 6'  # Runs sat 8pm ist

# you can declare env variables in 3 levels: workflow, job, step
env:
  ENV1: " ### workflow *level* env var ###"

jobs:  
  job1:
    runs-on: ubuntu-latest
    env:
      ENV2: " ### job *level* env ###"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello to third workflow
        env:
          ENV3: " ### step *level* env ###"
        run: echo "Using env -> {{ env.ENV1}}. @@ $ENV2. @@@ $ENV3"

      - name: multi line script
        run: |
         echo "This is {{ env.ENV2 }} and {{ env.ENV1 }} "
         echo "This is line 2"
         echo "This is @@ $ENV3. @@@ "

